/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs/queue/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear pending analysis queue entries */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Number of queue entries removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cleared: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/active/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel all active analysis jobs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Number of active jobs cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cancelled: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gateway health check
         * @description Returns the gateway service status and configured LLM provider.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List diagnosable Kubernetes resources
         * @description Returns names for the selected resource kind and namespace.
         */
        get: operations["listTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cluster/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check target cluster connectivity and collector permissions
         * @description Returns the resolved auth mode, API server, context, and required read checks.
         */
        get: operations["getClusterStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List analysis jobs
         * @description Returns a paginated list of jobs, optionally filtered by status.
         */
        get: operations["listJobs"];
        put?: never;
        /**
         * Create a new analysis job
         * @description Starts an asynchronous analysis pipeline for the specified pod.
         *     Returns immediately with a job_id. The frontend subscribes to
         *     the SSE stream to receive live stage updates.
         *
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job state
         * @description Returns the current state of a specific job.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel one active analysis job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current terminal job state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["job_state"];
                    };
                };
                /** @description Job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                500: components["responses"]["internal_error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream job events via SSE
         * @description Opens a Server-Sent Events (SSE) connection that receives live
         *     job stage transitions. The frontend's EventSource API connects
         *     to this endpoint and renders a pipeline timeline.
         *
         *     The connection stays open until the job reaches `done` or
         *     `failed`, at which point a final event is sent and the stream
         *     closes.
         *
         *     Event types:
         *       - `stage`: A stage transition (collecting, processing, llm_call, persisting)
         *       - `done`: Job completed successfully (includes incident_id)
         *       - `failed`: Job failed (includes error message)
         *
         *     All event payloads are JSON with snake_case field names.
         *
         *     Required headers for proxies:
         *       X-Accel-Buffering: no
         *       Cache-Control: no-cache
         *
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List incident reports
         * @description Returns a paginated list of report summaries.
         */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single incident report
         * @description Returns the full incident report including all nested evidence.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available fault scenarios
         * @description Returns all fault scenarios from k8s/scenarios/.
         */
        get: operations["listScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a fault scenario to the cluster
         * @description Applies the fault YAML to the demo deployment via kubectl patch.
         *     This modifies the cluster state — the pod will start failing.
         *
         */
        post: operations["applyScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset cluster to healthy baseline
         * @description Removes any applied fault and re-applies the base manifests.
         */
        post: operations["resetScenarios"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remediations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a dry-run remediation proposal
         * @description Creates a typed proposal without changing cluster state.
         */
        post: operations["createRemediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remediations/{remediation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a remediation proposal and audit state */
        get: operations["getRemediation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remediations/{remediation_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve and apply a remediation proposal */
        post: operations["approveRemediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remediations/{remediation_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a remediation proposal */
        post: operations["rejectRemediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard statistics
         * @description Returns aggregate metrics for the dashboard.
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the active LLM provider configuration
         * @description Returns the active provider, any model override, and per-provider
         *     availability. API key values are never returned.
         *
         */
        get: operations["getSettings"];
        put?: never;
        /**
         * Update the active LLM provider configuration
         * @description Sets the active provider and optionally stores or clears an API
         *     key and model override. Used by the frontend Settings page.
         *     Stored keys are never echoed in the response.
         *
         */
        post: operations["saveSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured LLM providers
         * @description Returns all providers with their availability status (whether a
         *     usable API key is set). Never returns key values.
         *
         */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Classification of the failure type. Exactly 8 values.
         *     Parity: SQLite CHECK, Pydantic Literal, TypeScript union.
         *
         * @enum {string}
         */
        failure_category: "crash" | "config" | "dependency" | "network" | "image" | "resource" | "probe" | "unknown";
        /**
         * @description Incident severity level. Exactly 4 values.
         *     Parity: SQLite CHECK, Pydantic Literal, TypeScript union.
         *
         * @enum {string}
         */
        severity: "low" | "medium" | "high" | "critical";
        /**
         * @description Pipeline stage of an analysis job. Exactly 7 values.
         *     Parity: SQLite CHECK, Redis hash field, SSE event payload.
         *
         * @enum {string}
         */
        job_status_enum: "queued" | "collecting" | "processing" | "llm_call" | "persisting" | "done" | "failed";
        /**
         * @description Source of an evidence item. Exactly 4 values.
         *
         * @enum {string}
         */
        evidence_source: "pod_log" | "previous_pod_log" | "kubernetes_event" | "pod_status";
        /** @description A single piece of evidence extracted from Kubernetes diagnostics.
         *     Parity: SQLite (stored inside report_json), Pydantic EvidenceItem.
         *      */
        evidence_item: {
            source: components["schemas"]["evidence_source"];
            /**
             * @description Pod name the evidence was collected from.
             * @example demo-app-abc123
             */
            pod: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the evidence, if available.
             */
            timestamp?: string | null;
            /**
             * @description The evidence text (log line, event message, status excerpt).
             * @example Last State: Terminated, Reason: OOMKilled, Exit Code: 137
             */
            evidence: string;
        };
        /** @description The canonical incident report produced by the LLM analysis pipeline.
         *     This is the contract between every LLM provider and the rest of the
         *     system. Parity: SQLite incidents table (denormalised fields +
         *     report_json for nested fields), Pydantic IncidentReport.
         *      */
        incident_report: {
            /**
             * Format: uuid
             * @description UUIDv7 identifier for this incident report.
             * @example 01938a7c-1234-5678-9abc-def012345678
             */
            incident_id: string;
            /** @description Human-readable summary of the incident. */
            incident_summary: string;
            /** @description The most probable root cause, based on evidence. */
            likely_root_cause: string;
            /** @description The component most likely affected (pod, deployment, config). */
            affected_component: string;
            failure_category: components["schemas"]["failure_category"];
            severity: components["schemas"]["severity"];
            /**
             * Format: float
             * @description LLM confidence score, bounded [0.0, 1.0].
             * @example 0.85
             */
            confidence: number;
            /** @description At least one evidence item must be cited. */
            supporting_evidence: components["schemas"]["evidence_item"][];
            /** @description Recommended remediation action. */
            suggested_fix: string;
            /**
             * @description kubectl commands to execute for remediation.
             * @example [
             *       "kubectl patch deployment demo-app -n demo --type strategic -p '{...}'",
             *       "kubectl rollout status deployment/demo-app -n demo"
             *     ]
             */
            recommended_commands: string[];
            /** @description Optional typed remediation proposals. These are always dry-run
             *     checked and require explicit operator approval before mutation.
             *      */
            recommended_actions?: components["schemas"]["remediation_action"][];
            /** @description Steps a human should take to verify the fix. */
            human_verification_steps: string[];
            /** @description Safe, concise explanation of how the diagnosis was formed. */
            analysis_explanation?: components["schemas"]["analysis_explanation"] | null;
            /** @description Whether the analysis found an active error on the target. */
            active_error?: boolean;
            /**
             * @description Identifier of the LLM provider that produced the report.
             * @example deepseek
             */
            provider?: string | null;
            /**
             * @description Model identifier used by the provider for the analysis.
             * @example deepseek-chat
             */
            model?: string | null;
            target_kind?: components["schemas"]["target_kind"];
            /** @description Kubernetes resource name that was analysed. */
            target_name?: string | null;
            /**
             * Format: date-time
             * @description When the report was persisted (ISO 8601).
             */
            created_at: string;
        };
        /** @description Non-sensitive summary of the redacted evidence sent for analysis. */
        analysis_input_summary: {
            current_log_lines: number;
            previous_log_lines: number;
            has_pod_status: boolean;
            has_kubernetes_events: boolean;
            restart_count: number;
            related_pod_count: number;
            /** @description Whether the processor redaction step ran. */
            redaction_applied: boolean;
            /** @description Number of redaction markers in the model input. */
            redaction_count: number;
        };
        /** @description Evidence-backed audit explanation, not hidden chain-of-thought. */
        analysis_explanation: {
            /** @description Brief explanation connecting the assessment to the evidence. */
            rationale: string;
            /** @description Observable log, status, or event signals used in the assessment. */
            key_signals: string[];
            /** @description Missing evidence, ambiguity, or manual checks still required. */
            uncertainty: string;
            input_summary: components["schemas"]["analysis_input_summary"];
        };
        /** @description Summary of an incident report for list views. Excludes nested
         *     arrays (supporting_evidence, recommended_commands,
         *     human_verification_steps) to keep list payloads small.
         *      */
        report_summary: {
            /** Format: uuid */
            incident_id: string;
            namespace: string;
            pod_name: string;
            failure_category: components["schemas"]["failure_category"];
            severity: components["schemas"]["severity"];
            /** Format: float */
            confidence: number;
            incident_summary: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Request to start a new analysis job. Submitted by the frontend
         *     when the user clicks "Analyse".
         *      */
        analysis_request: {
            /**
             * @description Kubernetes namespace of the target pod.
             * @default demo
             * @example demo
             */
            namespace: string;
            /**
             * @description Name of the selected Kubernetes resource. For Pod targets, an
             *     application name can still be resolved by label selector
             *     (app={pod_name}).
             *
             * @example demo-app
             */
            pod_name: string;
            target_kind?: components["schemas"]["target_kind"];
        };
        /**
         * @description Kubernetes resource kind to diagnose.
         * @default Pod
         * @enum {string}
         */
        target_kind: "Pod" | "Deployment" | "ReplicaSet" | "StatefulSet" | "DaemonSet" | "Job" | "CronJob" | "Service" | "Namespace" | "Node";
        target_option: {
            name: string;
            kind: components["schemas"]["target_kind"];
            namespace?: string | null;
        };
        target_list_response: {
            items: components["schemas"]["target_option"][];
        };
        /** @description Response when a new analysis job is created. */
        job_created: {
            /**
             * Format: uuid
             * @description UUIDv7 identifier for the job.
             */
            job_id: string;
            status: components["schemas"]["job_status_enum"];
        };
        /** @description Full job state. Parity: Redis hash (job:{job_id}), SQLite
         *     analysis_jobs table.
         *      */
        job_state: {
            /** Format: uuid */
            job_id: string;
            namespace: string;
            pod_name: string;
            /** @description Kubernetes resource kind being analysed. */
            target_kind?: components["schemas"]["target_kind"];
            status: components["schemas"]["job_status_enum"];
            /** @description Human-readable stage detail (e.g. "Calling DeepSeek deepseek-chat"). */
            stage?: string | null;
            /**
             * Format: uuid
             * @description Populated when status = done; absent otherwise.
             */
            incident_id?: string | null;
            /**
             * Format: int32
             * @description Total pipeline wall time in milliseconds.
             */
            latency_ms?: number | null;
            /** @description Error message when status = failed. */
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description SSE event payload for a stage transition. */
        sse_stage_event: {
            /** @enum {string} */
            event: "stage";
            /** Format: uuid */
            job_id: string;
            status: components["schemas"]["job_status_enum"];
            /** @description Human-readable stage detail. */
            stage?: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description SSE event payload for job completion. */
        sse_done_event: {
            /** @enum {string} */
            event: "done";
            /** Format: uuid */
            job_id: string;
            /** @enum {string} */
            status: "done";
            /** Format: uuid */
            incident_id: string;
            failure_category?: components["schemas"]["failure_category"];
            severity?: components["schemas"]["severity"];
            /** @default true */
            active_error: boolean;
            /** Format: int32 */
            latency_ms?: number;
        };
        /** @description SSE event payload for job failure. */
        sse_failed_event: {
            /** @enum {string} */
            event: "failed";
            /** Format: uuid */
            job_id: string;
            /** @enum {string} */
            status: "failed";
            error: string;
            /** Format: int32 */
            latency_ms?: number;
        };
        /** @description Summary of a fault scenario. */
        scenario_summary: {
            /**
             * @description Directory name under k8s/scenarios/.
             * @example 05-oom
             */
            scenario_id: string;
            /**
             * @description Human-readable scenario name.
             * @example OOM Killed
             */
            name: string;
            category: components["schemas"]["failure_category"];
            /**
             * @description What the fault does.
             * @example Memory limit reduced to 32Mi causing OOMKilled.
             */
            description: string;
            severity?: components["schemas"]["severity"];
        };
        scenario_apply_response: {
            applied: boolean;
            scenario_id: string;
            /** @description Human-readable description of the applied fault. */
            fault_description?: string;
        };
        /** @description A bounded Kubernetes change; arbitrary shell commands are not accepted. */
        remediation_action: {
            /** @enum {string} */
            action_type: "rollout_restart" | "set_deployment_resources" | "set_deployment_image" | "set_deployment_probe";
            namespace: string;
            deployment_name: string;
            container_name?: string | null;
            image?: string | null;
            cpu_request?: string | null;
            cpu_limit?: string | null;
            memory_request?: string | null;
            memory_limit?: string | null;
            /** @enum {string|null} */
            probe_type?: "readiness" | "liveness" | "startup" | null;
            probe_path?: string | null;
        };
        remediation_create_request: {
            action: components["schemas"]["remediation_action"];
            /** @default operator */
            requested_by: string;
        };
        remediation_approval_request: {
            /** @default operator */
            approved_by: string;
            /** @default false */
            confirm: boolean;
        };
        remediation_record: {
            /** Format: uuid */
            remediation_id: string;
            action: components["schemas"]["remediation_action"];
            /** @enum {string} */
            status: "pending" | "rejected" | "applying" | "applied" | "failed";
            requested_by: string;
            approved_by?: string | null;
            dry_run_output: string;
            result: string;
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Dashboard statistics aggregate. */
        stats_response: {
            /** Format: int32 */
            total_reports: number;
            /** Format: int32 */
            reports_24h: number;
            /** Format: float */
            mean_latency_ms: number;
            /** Format: float */
            mean_confidence: number;
            /**
             * @description Map of failure_category → count.
             * @example {
             *       "crash": 3,
             *       "config": 5,
             *       "resource": 2
             *     }
             */
            category_counts: {
                [key: string]: number;
            };
            latency_series?: {
                /** Format: date-time */
                timestamp?: string;
                /** Format: int32 */
                latency_ms?: number;
            }[];
        };
        health_response: {
            /** @enum {string} */
            status: "ok";
            /** @example gateway-svc */
            service: string;
            /** @example 0.1.0 */
            version: string;
            /** @description LLM provider name (only present on llm-svc and gateway). */
            provider?: string | null;
            /** @description K8s cluster connectivity status (connected | unreachable). */
            cluster?: string | null;
        };
        /** @description Information about a configured LLM provider. */
        provider_info: {
            /** @enum {string} */
            id: "mock" | "openai" | "anthropic" | "deepseek" | "openrouter";
            /** @example OpenAI */
            name: string;
            /** @example gpt-4o-mini */
            model: string;
            /** @description Whether a usable API key is configured for this provider
             *     (from the runtime config file or the environment).
             *      */
            available: boolean;
            /** @description Current model choices supported by this provider. */
            models?: {
                id: string;
                name: string;
            }[];
        };
        /** @description Request to update the runtime LLM provider configuration.
         *     The active provider, an optional API key and an optional model
         *     override can be set. API keys are stored server-side and are
         *     never returned by any GET endpoint.
         *      */
        provider_config_request: {
            /**
             * @description The provider to activate for future analyses.
             * @enum {string}
             */
            provider: "mock" | "openai" | "anthropic" | "deepseek" | "openrouter";
            /** @description API key for the selected provider. When present, it is
             *     persisted (overwriting any stored key). Omit to keep the
             *     stored key.
             *      */
            api_key?: string;
            /**
             * @description When true, removes any stored API key for the selected
             *     provider. Ignored when api_key is present.
             *
             * @default false
             */
            clear_key: boolean;
            /** @description Model override for the selected provider. When absent, the
             *     current value is kept; when null, the default is restored.
             *      */
            model?: string | null;
        };
        /** @description Runtime LLM configuration status. Never contains API key values —
         *     only whether each provider is available.
         *      */
        llm_config_status: {
            /**
             * @description The active provider for future analyses.
             * @enum {string}
             */
            provider: "mock" | "openai" | "anthropic" | "deepseek" | "openrouter";
            /** @description Active model override, if any. */
            model?: string | null;
            /**
             * @description Whether the active provider comes from the runtime config file or the environment.
             * @enum {string}
             */
            source?: "file" | "env";
            providers: components["schemas"]["provider_info"][];
        };
        pagination_meta: {
            /**
             * Format: int32
             * @description Total number of items matching the query (before pagination).
             */
            count: number;
            /**
             * Format: int32
             * @description Maximum items returned in this response.
             */
            limit: number;
            /**
             * Format: int32
             * @description Number of items skipped from the start.
             */
            offset: number;
        };
        /** @description RFC 7807 Problem Details JSON. */
        error: {
            /**
             * @description URI identifying the error type.
             * @example https://errors.k8s-llm.io/job-not-found
             */
            type: string;
            /**
             * @description Short human-readable summary of the error.
             * @example Job not found
             */
            title: string;
            /**
             * @description HTTP status code.
             * @example 404
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence.
             * @example No job exists with job_id 'abc123'
             */
            detail: string;
            /**
             * @description URI identifying the specific occurrence of the problem.
             * @example /api/jobs/abc123
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Internal server error */
        internal_error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "type": "https://errors.k8s-llm.io/internal",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred"
                 *     } */
                "application/json": components["schemas"]["error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "status": "ok",
                     *       "service": "gateway-svc",
                     *       "version": "0.1.0",
                     *       "provider": "deepseek"
                     *     } */
                    "application/json": components["schemas"]["health_response"];
                };
            };
        };
    };
    listTargets: {
        parameters: {
            query: {
                kind: components["schemas"]["target_kind"];
                /** @description Namespace for namespaced resources. Omit for cluster-scoped resources. */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["target_list_response"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    getClusterStatus: {
        parameters: {
            query?: {
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target cluster status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        cluster: "connected" | "unreachable";
                        mode: string;
                        kubeconfig?: string | null;
                        context?: string | null;
                        server?: string | null;
                        namespace: string;
                        permissions: {
                            [key: string]: boolean;
                        };
                    };
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description Filter by job status. */
                status?: components["schemas"]["job_status_enum"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["job_state"][];
                        /** Format: int32 */
                        count: number;
                        /** Format: int32 */
                        limit: number;
                        /** Format: int32 */
                        offset: number;
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "namespace": "demo",
                 *       "pod_name": "demo-app"
                 *     } */
                "application/json": components["schemas"]["analysis_request"];
            };
        };
        responses: {
            /** @description Job created and queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "job_id": "01938a7b-1234-5678-9abc-def012345678",
                     *       "status": "queued"
                     *     } */
                    "application/json": components["schemas"]["job_created"];
                };
            };
            /** @description Invalid request (missing required fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current job state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["job_state"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of job events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    listReports: {
        parameters: {
            query?: {
                namespace?: string;
                pod_name?: string;
                category?: components["schemas"]["failure_category"];
                severity?: components["schemas"]["severity"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of report summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["report_summary"][];
                        /** Format: int32 */
                        count: number;
                        /** Format: int32 */
                        limit: number;
                        /** Format: int32 */
                        offset: number;
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full incident report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["incident_report"];
                };
            };
            /** @description Report not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scenarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["scenario_summary"][];
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    applyScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario applied successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "applied": true,
                     *       "scenario_id": "05-oom",
                     *       "fault_description": "Memory limit reduced to 32Mi"
                     *     } */
                    "application/json": components["schemas"]["scenario_apply_response"];
                };
            };
            /** @description Scenario not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description This scenario is already applied. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    resetScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        reset: boolean;
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    createRemediation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["remediation_create_request"];
            };
        };
        responses: {
            /** @description Dry-run proposal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["remediation_record"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description Dry-run rejected by policy or Kubernetes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    getRemediation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remediation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Remediation record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["remediation_record"];
                };
            };
            /** @description Remediation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    approveRemediation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remediation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["remediation_approval_request"];
            };
        };
        responses: {
            /** @description Remediation applied or failed with audit result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["remediation_record"];
                };
            };
            /** @description Proposal is no longer pending or is already applying */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    rejectRemediation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                remediation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["remediation_approval_request"];
            };
        };
        responses: {
            /** @description Proposal rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["remediation_record"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: {
                /** @description Time range for statistics. */
                range?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["stats_response"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current LLM configuration status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["llm_config_status"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    saveSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "provider": "openai",
                 *       "api_key": "sk-...",
                 *       "model": "gpt-4o-mini"
                 *     } */
                "application/json": components["schemas"]["provider_config_request"];
            };
        };
        responses: {
            /** @description Configuration updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["llm_config_status"];
                };
            };
            /** @description Invalid provider or model */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["provider_info"][];
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
}
