/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gateway health check
         * @description Returns the gateway service status and configured LLM provider.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List analysis jobs
         * @description Returns a paginated list of jobs, optionally filtered by status.
         */
        get: operations["listJobs"];
        put?: never;
        /**
         * Create a new analysis job
         * @description Starts an asynchronous analysis pipeline for the specified pod.
         *     Returns immediately with a job_id. The frontend subscribes to
         *     the SSE stream to receive live stage updates.
         *
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job state
         * @description Returns the current state of a specific job.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream job events via SSE
         * @description Opens a Server-Sent Events (SSE) connection that receives live
         *     job stage transitions. The frontend's EventSource API connects
         *     to this endpoint and renders a pipeline timeline.
         *
         *     The connection stays open until the job reaches `done` or
         *     `failed`, at which point a final event is sent and the stream
         *     closes.
         *
         *     Event types:
         *       - `stage`: A stage transition (collecting, processing, llm_call, persisting)
         *       - `done`: Job completed successfully (includes incident_id)
         *       - `failed`: Job failed (includes error message)
         *
         *     All event payloads are JSON with snake_case field names.
         *
         *     Required headers for proxies:
         *       X-Accel-Buffering: no
         *       Cache-Control: no-cache
         *
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List incident reports
         * @description Returns a paginated list of report summaries.
         */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single incident report
         * @description Returns the full incident report including all nested evidence.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available fault scenarios
         * @description Returns all fault scenarios from k8s/scenarios/.
         */
        get: operations["listScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a fault scenario to the cluster
         * @description Applies the fault YAML to the demo deployment via kubectl patch.
         *     This modifies the cluster state — the pod will start failing.
         *
         */
        post: operations["applyScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset cluster to healthy baseline
         * @description Removes any applied fault and re-applies the base manifests.
         */
        post: operations["resetScenarios"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard statistics
         * @description Returns aggregate metrics for the dashboard.
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Classification of the failure type. Exactly 8 values.
         *     Parity: SQLite CHECK, Pydantic Literal, TypeScript union.
         *
         * @enum {string}
         */
        failure_category: "crash" | "config" | "dependency" | "network" | "image" | "resource" | "probe" | "unknown";
        /**
         * @description Incident severity level. Exactly 4 values.
         *     Parity: SQLite CHECK, Pydantic Literal, TypeScript union.
         *
         * @enum {string}
         */
        severity: "low" | "medium" | "high" | "critical";
        /**
         * @description Pipeline stage of an analysis job. Exactly 7 values.
         *     Parity: SQLite CHECK, Redis hash field, SSE event payload.
         *
         * @enum {string}
         */
        job_status_enum: "queued" | "collecting" | "processing" | "llm_call" | "persisting" | "done" | "failed";
        /**
         * @description Source of an evidence item. Exactly 4 values.
         *
         * @enum {string}
         */
        evidence_source: "pod_log" | "previous_pod_log" | "kubernetes_event" | "pod_status";
        /** @description A single piece of evidence extracted from Kubernetes diagnostics.
         *     Parity: SQLite (stored inside report_json), Pydantic EvidenceItem.
         *      */
        evidence_item: {
            source: components["schemas"]["evidence_source"];
            /**
             * @description Pod name the evidence was collected from.
             * @example demo-app-abc123
             */
            pod: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the evidence, if available.
             */
            timestamp?: string | null;
            /**
             * @description The evidence text (log line, event message, status excerpt).
             * @example Last State: Terminated, Reason: OOMKilled, Exit Code: 137
             */
            evidence: string;
        };
        /** @description The canonical incident report produced by the LLM analysis pipeline.
         *     This is the contract between every LLM provider and the rest of the
         *     system. Parity: SQLite incidents table (denormalised fields +
         *     report_json for nested fields), Pydantic IncidentReport.
         *      */
        incident_report: {
            /**
             * Format: uuid
             * @description UUIDv7 identifier for this incident report.
             * @example 01938a7c-1234-5678-9abc-def012345678
             */
            incident_id: string;
            /** @description Human-readable summary of the incident. */
            incident_summary: string;
            /** @description The most probable root cause, based on evidence. */
            likely_root_cause: string;
            /** @description The component most likely affected (pod, deployment, config). */
            affected_component: string;
            failure_category: components["schemas"]["failure_category"];
            severity: components["schemas"]["severity"];
            /**
             * Format: float
             * @description LLM confidence score, bounded [0.0, 1.0].
             * @example 0.85
             */
            confidence: number;
            /** @description At least one evidence item must be cited. */
            supporting_evidence: components["schemas"]["evidence_item"][];
            /** @description Recommended remediation action. */
            suggested_fix: string;
            /**
             * @description kubectl commands to execute for remediation.
             * @example [
             *       "kubectl patch deployment demo-app -n demo --type strategic -p '{...}'",
             *       "kubectl rollout status deployment/demo-app -n demo"
             *     ]
             */
            recommended_commands: string[];
            /** @description Steps a human should take to verify the fix. */
            human_verification_steps: string[];
            /**
             * Format: date-time
             * @description When the report was persisted (ISO 8601).
             */
            created_at: string;
        };
        /** @description Summary of an incident report for list views. Excludes nested
         *     arrays (supporting_evidence, recommended_commands,
         *     human_verification_steps) to keep list payloads small.
         *      */
        report_summary: {
            /** Format: uuid */
            incident_id: string;
            namespace: string;
            pod_name: string;
            failure_category: components["schemas"]["failure_category"];
            severity: components["schemas"]["severity"];
            /** Format: float */
            confidence: number;
            incident_summary: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Request to start a new analysis job. Submitted by the frontend
         *     when the user clicks "Analyse".
         *      */
        analysis_request: {
            /**
             * @description Kubernetes namespace of the target pod.
             * @default demo
             * @example demo
             */
            namespace: string;
            /**
             * @description Pod name or deployment name. If the exact pod name is not found,
             *     the collector resolves it by label selector (app={pod_name}).
             *
             * @example demo-app
             */
            pod_name: string;
        };
        /** @description Response when a new analysis job is created. */
        job_created: {
            /**
             * Format: uuid
             * @description UUIDv7 identifier for the job.
             */
            job_id: string;
            status: components["schemas"]["job_status_enum"];
        };
        /** @description Full job state. Parity: Redis hash (job:{job_id}), SQLite
         *     analysis_jobs table.
         *      */
        job_state: {
            /** Format: uuid */
            job_id: string;
            namespace: string;
            pod_name: string;
            status: components["schemas"]["job_status_enum"];
            /** @description Human-readable stage detail (e.g. "Calling DeepSeek deepseek-chat"). */
            stage?: string | null;
            /**
             * Format: uuid
             * @description Populated when status = done; absent otherwise.
             */
            incident_id?: string | null;
            /**
             * Format: int32
             * @description Total pipeline wall time in milliseconds.
             */
            latency_ms?: number | null;
            /** @description Error message when status = failed. */
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description SSE event payload for a stage transition. */
        sse_stage_event: {
            /** @enum {string} */
            event: "stage";
            /** Format: uuid */
            job_id: string;
            status: components["schemas"]["job_status_enum"];
            /** @description Human-readable stage detail. */
            stage?: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description SSE event payload for job completion. */
        sse_done_event: {
            /** @enum {string} */
            event: "done";
            /** Format: uuid */
            job_id: string;
            /** @enum {string} */
            status: "done";
            /** Format: uuid */
            incident_id: string;
            failure_category?: components["schemas"]["failure_category"];
            severity?: components["schemas"]["severity"];
            /** Format: int32 */
            latency_ms?: number;
        };
        /** @description SSE event payload for job failure. */
        sse_failed_event: {
            /** @enum {string} */
            event: "failed";
            /** Format: uuid */
            job_id: string;
            /** @enum {string} */
            status: "failed";
            error: string;
            /** Format: int32 */
            latency_ms?: number;
        };
        /** @description Summary of a fault scenario. */
        scenario_summary: {
            /**
             * @description Directory name under k8s/scenarios/.
             * @example 05-oom
             */
            scenario_id: string;
            /**
             * @description Human-readable scenario name.
             * @example OOM Killed
             */
            name: string;
            category: components["schemas"]["failure_category"];
            /**
             * @description What the fault does.
             * @example Memory limit reduced to 32Mi causing OOMKilled.
             */
            description: string;
            severity?: components["schemas"]["severity"];
        };
        scenario_apply_response: {
            applied: boolean;
            scenario_id: string;
            /** @description Human-readable description of the applied fault. */
            fault_description?: string;
        };
        /** @description Dashboard statistics aggregate. */
        stats_response: {
            /** Format: int32 */
            total_reports: number;
            /** Format: int32 */
            reports_24h: number;
            /** Format: float */
            mean_latency_ms: number;
            /** Format: float */
            mean_confidence: number;
            /**
             * @description Map of failure_category → count.
             * @example {
             *       "crash": 3,
             *       "config": 5,
             *       "resource": 2
             *     }
             */
            category_counts: {
                [key: string]: number;
            };
            latency_series?: {
                /** Format: date-time */
                timestamp?: string;
                /** Format: int32 */
                latency_ms?: number;
            }[];
        };
        health_response: {
            /** @enum {string} */
            status: "ok";
            /** @example gateway-svc */
            service: string;
            /** @example 0.1.0 */
            version: string;
            /** @description LLM provider name (only present on llm-svc and gateway). */
            provider?: string | null;
        };
        pagination_meta: {
            /**
             * Format: int32
             * @description Total number of items matching the query (before pagination).
             */
            count: number;
            /**
             * Format: int32
             * @description Maximum items returned in this response.
             */
            limit: number;
            /**
             * Format: int32
             * @description Number of items skipped from the start.
             */
            offset: number;
        };
        /** @description RFC 7807 Problem Details JSON. */
        error: {
            /**
             * @description URI identifying the error type.
             * @example https://errors.k8s-llm.io/job-not-found
             */
            type: string;
            /**
             * @description Short human-readable summary of the error.
             * @example Job not found
             */
            title: string;
            /**
             * @description HTTP status code.
             * @example 404
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence.
             * @example No job exists with job_id 'abc123'
             */
            detail: string;
            /**
             * @description URI identifying the specific occurrence of the problem.
             * @example /api/jobs/abc123
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Internal server error */
        internal_error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "type": "https://errors.k8s-llm.io/internal",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred"
                 *     } */
                "application/json": components["schemas"]["error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "status": "ok",
                     *       "service": "gateway-svc",
                     *       "version": "0.1.0",
                     *       "provider": "deepseek"
                     *     } */
                    "application/json": components["schemas"]["health_response"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description Filter by job status. */
                status?: components["schemas"]["job_status_enum"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["job_state"][];
                        /** Format: int32 */
                        count: number;
                        /** Format: int32 */
                        limit: number;
                        /** Format: int32 */
                        offset: number;
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "namespace": "demo",
                 *       "pod_name": "demo-app"
                 *     } */
                "application/json": components["schemas"]["analysis_request"];
            };
        };
        responses: {
            /** @description Job created and queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "job_id": "01938a7b-1234-5678-9abc-def012345678",
                     *       "status": "queued"
                     *     } */
                    "application/json": components["schemas"]["job_created"];
                };
            };
            /** @description Invalid request (missing required fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current job state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["job_state"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of job events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    listReports: {
        parameters: {
            query?: {
                namespace?: string;
                pod_name?: string;
                category?: components["schemas"]["failure_category"];
                severity?: components["schemas"]["severity"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of report summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["report_summary"][];
                        /** Format: int32 */
                        count: number;
                        /** Format: int32 */
                        limit: number;
                        /** Format: int32 */
                        offset: number;
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full incident report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["incident_report"];
                };
            };
            /** @description Report not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scenarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["scenario_summary"][];
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    applyScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario applied successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "applied": true,
                     *       "scenario_id": "05-oom",
                     *       "fault_description": "Memory limit reduced to 32Mi"
                     *     } */
                    "application/json": components["schemas"]["scenario_apply_response"];
                };
            };
            /** @description Scenario not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description A scenario is already applied. Reset first. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    resetScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        reset: boolean;
                    };
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
    getStats: {
        parameters: {
            query?: {
                /** @description Time range for statistics. */
                range?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["stats_response"];
                };
            };
            500: components["responses"]["internal_error"];
        };
    };
}
