-- ============================================================================
-- SQLite State Contract — K8s LLM Incident Analyser
-- ============================================================================
-- This file is the Single Source of Truth for the relational state of the
-- platform. It is consumed by:
--   - reports-svc (owns the database, executes these statements on startup)
--   - orchestrator-svc (reads analysis_jobs via reports-svc API, never direct)
--   - Frontend (indirectly, via the reports-svc OpenAPI contract)
--
-- Database: SQLite 3.40+ (WAL mode for concurrent reads during writes)
-- ID format: UUIDv7 strings (time-sortable, generated by uuid_utils.uuid7())
-- Naming: snake_case everywhere (column names, index names, trigger names)
-- Timestamps: ISO 8601 text strings (SQLite has no native datetime type)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PRAGMA: Write-Ahead Logging for concurrent read access
-- ----------------------------------------------------------------------------
-- reports-svc is the single writer. Other services and the gateway may read
-- concurrently (e.g. GET /api/reports). WAL mode allows readers to proceed
-- without blocking the writer. This is safe at dissertation scale (~10
-- analyses/day). Migration to PostgreSQL is a v2 concern.
-- ----------------------------------------------------------------------------
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;
PRAGMA encoding = "UTF-8";

-- ============================================================================
-- Table: incidents
-- ============================================================================
-- One row per completed IncidentReport. Populated by reports-svc when the
-- orchestrator calls POST /reports with a validated IncidentReport.
--
-- The full IncidentReport JSON (including supporting_evidence array,
-- recommended_commands, human_verification_steps) is stored in report_json
-- as a TEXT column. Indexed columns are extracted for filtering and
-- aggregation. This avoids normalising the nested evidence array into a
-- separate table — the evidence is always read alongside the report, never
-- queried independently.
-- ============================================================================
CREATE TABLE IF NOT EXISTS incidents (

    -- Primary key: UUIDv7 string (time-sortable, collision-proof)
    -- Generated by the LLM provider or reports-svc before insert
    incident_id        TEXT    PRIMARY KEY,

    -- K8s metadata: used for filtering reports by namespace/pod
    namespace          TEXT    NOT NULL,
    pod_name           TEXT    NOT NULL,

    -- Classification fields: extracted from report_json for indexing
    -- Enum parity: exactly 8 values, matching OpenAPI enum and Pydantic Literal
    failure_category   TEXT    NOT NULL CHECK (
        failure_category IN (
            'crash', 'config', 'dependency', 'network',
            'image', 'resource', 'probe', 'unknown'
        )
    ),

    -- Enum parity: exactly 4 values, matching OpenAPI enum and Pydantic Literal
    severity           TEXT    NOT NULL CHECK (
        severity IN ('low', 'medium', 'high', 'critical')
    ),

    -- Confidence: bounded float [0.0, 1.0], matching OpenAPI minimum/maximum
    confidence         REAL    NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),

    -- Denormalised summary fields: extracted for dashboard display without
    -- parsing report_json. These are NOT redundant — they enable fast list
    -- views and stat queries.
    incident_summary   TEXT    NOT NULL,
    likely_root_cause  TEXT    NOT NULL,
    affected_component TEXT    NOT NULL,
    suggested_fix      TEXT    NOT NULL,

    -- Full IncidentReport as JSON string (includes supporting_evidence,
    -- recommended_commands, human_verification_steps — the nested fields
    -- that are not worth normalising into separate tables at this scale).
    -- Stored as TEXT because SQLite has no native JSONB type.
    report_json        TEXT    NOT NULL,

    -- Auditing fields (D7: created_at + updated_at only, no soft delete,
    -- no actor fields — auth deferred to v2)
    created_at         TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at         TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Indexes: optimise the query patterns used by the dashboard and reports list
CREATE INDEX IF NOT EXISTS idx_incidents_ns_pod     ON incidents (namespace, pod_name);
CREATE INDEX IF NOT EXISTS idx_incidents_category   ON incidents (failure_category);
CREATE INDEX IF NOT EXISTS idx_incidents_created    ON incidents (created_at DESC);

-- ============================================================================
-- Table: analysis_jobs
-- ============================================================================
-- One row per analysis job (async pipeline). The orchestrator creates a job
-- when POST /api/jobs is called, then updates status as the pipeline
-- progresses through stages: queued → collecting → processing → llm_call →
-- persisting → done (or → failed).
--
-- Redis is the primary job state store (low-latency pub/sub for SSE). This
-- table is a durable snapshot written by reports-svc on behalf of the
-- orchestrator, used for:
--   - GET /api/jobs (list with pagination, filtering by status)
--   - GET /api/stats (dashboard latency aggregates)
--   - Post-mortem analysis (which jobs failed, how long they took)
--
-- The orchestrator never writes to SQLite directly — it calls reports-svc's
-- POST /jobs endpoint, which owns the database connection.
-- ============================================================================
CREATE TABLE IF NOT EXISTS analysis_jobs (

    -- Primary key: UUIDv7 string
    job_id             TEXT    PRIMARY KEY,

    -- K8s metadata: what was being analysed
    namespace          TEXT    NOT NULL,
    pod_name           TEXT    NOT NULL,

    -- Pipeline status: 7 values, matching OpenAPI enum and Redis hash field
    -- queued:          job created, not yet started
    -- collecting:      collector-svc gathering kubectl evidence
    -- processing:      processor-svc filtering + redacting
    -- llm_call:        llm-svc calling the LLM provider
    -- persisting:      reports-svc writing the IncidentReport
    -- done:            pipeline completed successfully
    -- failed:          pipeline failed at some stage (see error field)
    status             TEXT    NOT NULL CHECK (
        status IN (
            'queued', 'collecting', 'processing',
            'llm_call', 'persisting', 'done', 'failed'
        )
    ),

    -- Human-readable stage detail (e.g. "Calling DeepSeek deepseek-chat")
    -- Nullable because queued jobs have no stage yet
    stage              TEXT,

    -- Foreign key to incidents: nullable until the job reaches 'done' status
    -- On done, the orchestrator saves the IncidentReport first, then links
    -- the job to it. On failed, this remains NULL.
    incident_id        TEXT    REFERENCES incidents (incident_id),

    -- Total pipeline wall time in milliseconds (populated on done or failed)
    latency_ms         INTEGER,

    -- Error message if status = 'failed', NULL otherwise
    error              TEXT,

    -- Auditing fields
    created_at         TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at         TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_jobs_status    ON analysis_jobs (status);
CREATE INDEX IF NOT EXISTS idx_jobs_created   ON analysis_jobs (created_at DESC);

-- ============================================================================
-- Triggers: auto-update updated_at on row modification
-- ============================================================================
-- Every UPDATE to either table automatically sets updated_at to the current
-- timestamp. This ensures the auditing field is never stale without
-- requiring application code to remember to set it.
-- ============================================================================

CREATE TRIGGER IF NOT EXISTS trg_incidents_updated
    AFTER UPDATE ON incidents
    FOR EACH ROW
    WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE incidents SET updated_at = datetime('now') WHERE rowid = NEW.rowid;
END;

CREATE TRIGGER IF NOT EXISTS trg_jobs_updated
    AFTER UPDATE ON analysis_jobs
    FOR EACH ROW
    WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE analysis_jobs SET updated_at = datetime('now') WHERE rowid = NEW.rowid;
END;

-- ============================================================================
-- Seed data: none required
-- ============================================================================
-- The database starts empty. Reports are populated as analyses complete.
-- Scenarios are not stored in the database — they are read from the
-- filesystem by scenario-svc (k8s/scenarios/*/fault.yaml).
-- ============================================================================
