apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  template:
    spec:
      containers:
      - name: demo-app
        env:
        - name: DATABASE_URL
          value: "postgresql://database.invalid:5432/db"
