apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  template:
    spec:
      containers:
      - name: demo-app
        env:
        - name: READ_ONLY_FS_FAULT
          value: "1"
        securityContext:
          readOnlyRootFilesystem: true
